
#ifndef __CONFIG_H__
#define __CONFIG_H__

#define CONFIG_ARMV7_PSCI_NR_CPUS 2
#define CONFIG_ARMV7_PSCI 1
#define CONFIG_MACH_SUN8I_R528 1
#define CONFIG_ARMV7_VIRT 1
#define CONFIG_COUNTER_FREQUENCY 24000000
#define CONFIG_ARM_GIC_BASE_ADDRESS 0x03020000
#define CONFIG_ARMV7_SECURE_BASE 0x00044000
#define CONFIG_SYS_CACHELINE_SIZE 64
#define CFG_SMP_PEN_ADDR 0

#define IS_ENABLED(option) (option)

#endif
